package com.quikflix.moviecatalog.domain;

import java.util.List;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Getter;
import lombok.Setter;

/**
 * MovieInfo class to represent an item in the movie_info table
 *
 */
@DynamoDBDocument
@DynamoDBTable(tableName = "movie_info")
@Getter
@Setter
public class MovieInfo {
	
	public MovieInfo(
			String name,
			String director,
			List<String> cast,
			String category,
			int year,
			String description ) {
		this.name = name;
		this.director = director;
		this.cast = cast;
		this.category = category;
		this.year = year;
		this.description = description;;
	}
	
	
	private String Id;
	
	// The attributes for the hash key must be set on the getter, couldn't use lombok for this method
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "Id")
	public String getId() {
		return this.Id;
	}
	
	@DynamoDBAttribute
	private String name;
	
	@DynamoDBAttribute
	private String director;
	
	@DynamoDBAttribute
	private List<String> cast;
	
	@DynamoDBAttribute
	private String category;
	
	@DynamoDBAttribute
	private int year;
	
	@DynamoDBAttribute
	private String description;	
}
