package com.quikflix.moviecatalog.domain;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import lombok.Getter;
import lombok.Setter;

/**
 * MovieInfo class to represent an item in the movie_info table
 *
 */
@DynamoDBDocument
@Getter
@Setter
public class MovieInfo {
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "Id")
	private String Id;
	
	@DynamoDBAttribute
	private String name;
	
	@DynamoDBAttribute
	private String director;
	
	@DynamoDBAttribute
	private List<String> cast;
	
	@DynamoDBAttribute
	private String category;
	
	@DynamoDBAttribute
	private String year;
	
	@DynamoDBAttribute
	private String description;	
}
